branch-defaults:
  master:
    environment: Datapublic-env-2
environment-defaults:
  Datapublic-env-2:
    branch: null
    repository: null
global:
  application_name: datapublic
  default_ec2_keyname: datapublic
  default_platform: Puma with Ruby 2.6 running on 64bit Amazon Linux
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
